apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosite
  labels:
    app: demosite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demosite
  template:
    metadata:
      labels:
        app: demosite
    spec:
      containers:
      - name: demosite
        image: ${GCR上に登録されたイメージ名:バージョン}
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5